# image: mileschou/php-testing-base:7.0

stages:
  - build
  # - test
  # - deploy

build-docker-image:
  stage: build

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/jasonwu070721/car_repair_api_gin .
    - docker push registry.gitlab.com/jasonwu070721/car_repair_api_gin
# build_job:
#   stage: build
#   script:
#     - echo "hello world, build!"
# - composer install
# cache:
#   untracked: true
# artifacts:
#   paths:
#     - vendor/

# test_job:
#   stage: test
#   script:
#     - echo "test"
#   # dependencies:
#   #   - build_job

# deploy_job:
#   stage: deploy
#   script:
#     - echo Deploy OK
# only:
#   - release
# when: manual
