image: docker

services:
  - docker:dind

stages:
  - build

build-docker-image:
  stage: build

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker build -t $CI_REGISTRY_IMAGE:1.0.0-build$CI_PIPELINE_IID .
    - docker tag $CI_REGISTRY_IMAGE:1.0.0-build$CI_PIPELINE_IID lastest
    - docker images
    - docker push $CI_REGISTRY_IMAGE:1.0.0-build$CI_PIPELINE_IID
    # - docker push $CI_REGISTRY_IMAGE:lastest

