# image: docker

# services:
#   - docker:dind

stages:
  - run

run-api:
  stage: run
  tags: 
    - aws
  before_script:
    - echo "before_script"
    - docker ps
  script:
    - echo "script"

# .build-push-image:
#   stage: push

#   before_script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
#   script:
#     - docker build -t $CI_REGISTRY_IMAGE:1.0.0-build$CI_PIPELINE_IID .
#     - docker tag $CI_REGISTRY_IMAGE:1.0.0-build$CI_PIPELINE_IID $CI_REGISTRY_IMAGE:latest
#     - docker images
#     - docker push $CI_REGISTRY_IMAGE:1.0.0-build$CI_PIPELINE_IID
#     - docker push $CI_REGISTRY_IMAGE:latest
